### ISSUE TITLE
Make it official?

### ISSUE THREAD

**Issue by NayamAmarshe** [nbuechner/upscayl-snap#1]
Hi Nils!
I came across the Upscayl snap page which led me here. Would you like to make it official?

**Comment by nbuechner** [comment]
Hey. Sounds great. Do you want to add it to your repo? I can rename/delist my snap if you want to add it yourself.
Or you just set a link to mine.

**Comment by NayamAmarshe** [comment]
I can add you to the Upscayl org, you can release the project under Upscayl's name :)

**Comment by nbuechner** [comment]
Ok lets do that then.

**Comment by nbuechner** [comment]
The owner has requested the name "upscayl" to be transferred to him. Closing this.
