### ISSUE TITLE
strange effects

### ISSUE THREAD

**Issue by Harfenklang** [nbuechner/upscayl-snap#2]
Hello, I had some very good results with upskayl, but after a few days only such pictures come out...!
What could be the error?

![15-05-_2023_10-25-07](https://github.com/nbuechner/upscayl-snap/assets/81568643/ce201ffe-448e-4919-b5ad-7ec939b3e4eb)

**Comment by nbuechner** [comment]
Are you sure this is a problem with snap packaging? In this case please open a bug at https://github.com/upscayl/snap
This repo is not used to build the snap.
If you also get strange results with for example the flatpak or AppImage please file a bug with as much log output as possible at https://github.com/upscayl/upscayl
